apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-kafka-test-reader
  namespace: min-side
  labels:
    team: min-side
spec:
  envFrom:
    - secret: tms-kafka-test-reader-secrets
  image: {{version}}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 30
  readiness:
    path: /internal/isReady
    initialDelay: 30
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  ingresses:
    - "https://tms-kafka-test-reader-gcp.nais.oera.no"
  webproxy: true
  resources:
    limits:
      cpu: "3"
      memory: 1200Mi
    requests:
      cpu: "1"
      memory: 1024Mi
  kafka:
    pool: nav-prod
  accessPolicy:
    outbound:
      external:
        - host: kafka-schema-registry.nais.adeo.no
